enum actionType {
	GETLOOKUPFIELDSDATA = 'GETLOOKUPFIELDSDATA',
	GETALLFIELDTYPE = 'GETALLFIELDTYPE',
	GETUSERDATAPREFERENCELIST = 'GETUSERDATAPREFERENCELIST',
	GETLANGUAGEDATASOURCES = 'GETLANGUAGEDATASOURCES',

	GETALLACTIVELIST = 'GETALLACTIVELIST',
	GETTREE = 'GETTREE'

}

export default actionType;
