enum actionType {
  GET_ALERT_INIT_WORKFLOW_STATUS = 'GET_ALERT_INIT_WORKFLOW_STATUS',

  ALL_ALERT_LIST_SUCCESS = 'ALL_ALERT_LIST_SUCCESS',
  ALL_ALERT_PAGINATION_SUCCESS = 'ALL_ALERT_PAGINATION_SUCCESS',
  ALL_SB_ALERT_RECENT_STATUS_SUCCESS = 'ALL_SB_ALERT_RECENT_STATUS_SUCCESS',
  ALL_SB_ALERT_CASE_STATUS_SUCCESS = 'ALL_SB_ALERT_CASE_STATUS_SUCCESS',
  ALL_RIGHT_PANE_RELATED_DATA_SUCCESS = 'ALL_RIGHT_PANE_RELATED_DATA_SUCCESS',
  ALL_RIGHT_PANE_HISTORY_DATA_SUCCESS = 'ALL_RIGHT_PANE_HISTORY_DATA_SUCCESS',
  TOP_BAR_TITLE_SELECTED_SB = 'TOP_BAR_TITLE_SELECTED_SB',
  ALERT_ID_SELECTED_SB = 'ALERT_ID_SELECTED_SB',
  COMMENT_HISTORY_SUCCESS = 'COMMENT_HISTORY_SUCCESS',
  SAVE_COMMENT_SUCCESS = 'SAVE_COMMENT_SUCCESS',
  FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS',
  ALL_ALERT_FILTER_LIST_SUCCESS = 'ALL_ALERT_FILTER_LIST_SUCCESS',
}

export default actionType;
