export enum actionType {
  GETRULESTATUS = 'GETRULESTATUS',
  GETSCENARIOSTATUS = 'GETSCENARIOSTATUS',
  ALL_DETECTION_LIST_SUCCESS = 'ALL_DETECTION_LIST_SUCCESS',
  ALL_SB_DETECTION_RULES_STATUS_SUCCESS = 'ALL_SB_DETECTION_RULES_STATUS_SUCCESS',
  ALL_SB_DETECTION_SCENARIOS_STATUS_SUCCESS = 'ALL_SB_DETECTION_SCENARIOS_STATUS_SUCCESS',
  ALL_SB_DETECTION_PROFILES_STATUS_SUCCESS = 'ALL_SB_DETECTION_PROFILES_STATUS_SUCCESS',
  DETECTION_ID_SELECTED_SB = 'DETECTION_ID_SELECTED_SB',
  DETECTION_NAME_SELECTED_SB = 'DETECTION_NAME_SELECTED_SB',
  // TOP_BAR_TITLE_SELECTED_SB= 'TOP_BAR_TITLE_SELECTED_SB'
}

export default actionType;
