export enum actionType {
  GET_LOGIN_INIT_CACHE = 'GET_LOGIN_INIT_CACHE',
  AUTHENTICATE_USER = 'AUTHENTICATE_USER',
  SHOW_LOGIN_ERR_MSG = 'SHOW_LOGIN_ERR_MSG',
  LOGOUT_USER = 'LOGOUT_USER',
  ALL_ALERT_USER_PREFERENCE = 'ALL_ALERT_USER_PREFERENCE',
  MANAGE_DEFAULT_DISPLAY = 'MANAGE_DEFAULT_DISPLAY'
}

export default actionType;
