enum actionType {
  SHOW_BOTTOM_NOTIFICATION = 'SHOW_BOTTOM_NOTIFICATION',
  SHOW_IS_LOADING = 'SHOW_IS_LOADING',
  HIDE_IS_LOADING = 'HIDE_IS_LOADING',
  SWITCHVIEW = 'SWITCHVIEW',
  SIDEBAR = 'SIDEBAR',
  CHANGETAB = 'CHANGETAB',
  RESETTAB = 'RESETTAB',
  USERMENU = 'USERMENU',
  GETALLAVAILABLEJOBS = 'GETALLAVAILABLEJOBS',
  ALLFILESJOB = 'ALLFILESJOB',
  GETINTERNALLISTSBYORGUNITFORJOBS = 'GETINTERNALLISTSBYORGUNITFORJOBS',
  ALLPATHJOB = 'ALLPATHJOB',
  GETPERMISSION = 'GETPERMISSION',
  GETPROFILENAMELIST = 'GETPROFILENAMELIST',
  ALLSCENARIOJOB = 'ALLSCENARIOJOB',
  GETALLTEMPLATES = 'GETALLTEMPLATES',
  AUDITACTION = 'AUDITACTION',
  GETALLACTIVELIST = 'GETALLACTIVELIST',
  POPOVER_CHILD_IS_AVAILABLE= 'POPOVER_CHILD_IS_AVAILABLE',
  POPOVER_CHILD_NOT_AVAILABLE= 'POPOVER_CHILD_NOT_AVAILABLE',
}

export default actionType;
