enum actionType  {
  ALL_ADMIN_DATALIST_SUCCESS = 'ALL_ADMIN_DATALIST_SUCCESS',
  ALL_ADMIN_RISKLIST_SUCCESS = 'ALL_ADMIN_RISKLIST_SUCCESS',
  ALL_ADMIN_ORGUNIT_LIST_SUCCESS = 'ALL_ADMIN_ORGUNIT_LIST_SUCCESS',
  ADMIN_RISK_MERGE_REQUEST_SUCCESS = 'ADMIN_RISK_MERGE_REQUEST_SUCCESS',
  ADMIN_LOG_CATAGORY_SUCCESS = 'ADMIN_LOG_CATAGORY_SUCCESS',
  ADD_USER_TO_MODIFY = 'ADD_USER_TO_MODIFY',
  EDIT_SCHEDULE_TO_MODIFY ='EDIT_SCHEDULE_TO_MODIFY',
  ADD_GROUP_TO_MODIFY= 'ADD_GROUP_TO_MODIFY',
  DELETE_GROUP_TO_MODIFY = 'DELETE_GROUP_TO_MODIFY',
  USER_UPDATE_HISTORY_SUCCESS = 'USER_UPDATE_HISTORY_SUCCESS',
  LOOKUP_COUNTRY_DATA_SUCCESS = 'LOOKUP_COUNTRY_DATA_SUCCESS',
  USER_UPDATE_SECURITY_SUCCESS = 'USER_UPDATE_SECURITY_SUCCESS'
}

export default actionType;
